### ISSUE TITLE
default level of zoom is wrong

### ISSUE THREAD

**Issue by olivier38070** [Siclo-Mobile/SCTiledImage#1]
Hi,

using the latest version, prepared tiles with n level of zoom.

default level of zoom displayed is always less, for one or more level than what exist on the "disk"

**Comment by comaxime** [comment]
hello @olivier38070 
What do you mean by "default level of zoom displayed"?

By the way, sorry the documentation has not been written yet

**Comment by ormaa** [comment]
Hi,

I closed this issue, as I found what was wrong.
I redo all my tiles, and now, the proper level is displayed, by default (when app starts)
thanks for feedback
Olivier

**Comment by ormaa** [comment]
oh, You need to close it please. I cannot :-)
